all:
  children:
    proxmox:
      hosts:
        proxmox.local:
    truenas:
      hosts:
        truenas.local:
    ubuntu_vms:
      hosts:
        dns.local:
        pihole.local:
        dockerhost.local:
        upsmon.local:

    raspberry_pi:
      hosts:
        pi1.local:
        pi2.local:
        pi3.local:
        pi4.local:
