---
# Example only for Ubuntu if it’s managing VLANs via Netplan
- name: Create VLAN interface (vlan20 for SERVERS)
  copy:
    dest: /etc/netplan/99-vlans.yaml
    content: |
      network:
        version: 2
        ethernets:
          enp3s0:
            dhcp4: no
        vlans:
          vlan20:
            id: 20
            link: enp3s0
            addresses: [192.168.20.2/24]
            gateway4: 192.168.20.1
            nameservers:
              addresses: [1.1.1.1, 1.0.0.1]

- name: Apply Netplan
  command: netplan apply
