---
- name: Create Pi-hole container directory
  file:
    path: /opt/pihole
    state: directory

- name: Copy Pi-hole Docker Compose file
  copy:
    dest: /opt/pihole/docker-compose.yml
    content: |
      version: "3"
      services:
        pihole:
          container_name: pihole
          image: pihole/pihole:latest
          environment:
            TZ: 'America/New_York'
            WEBPASSWORD: 'changeme'
          volumes:
            - './etc-pihole:/etc/pihole'
            - './etc-dnsmasq.d:/etc/dnsmasq.d'
          dns:
            - 127.0.0.1
            - 1.1.1.1
          ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "80:80"
          restart: unless-stopped

- name: Start Pi-hole using Docker Compose
  shell: docker compose up -d
  args:
    chdir: /opt/pihole
